// Package boilerplate provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package boilerplate

// API defines model for API.
type API struct {
	Api *string `json:"api,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code        *int64  `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
}

// RoomInfo defines model for RoomInfo.
type RoomInfo struct {
	Id   string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}

// CreateNewRoomJSONBody defines parameters for CreateNewRoom.
type CreateNewRoomJSONBody struct {
	Name string `json:"name,omitempty"`
}

// ConnectRoomParams defines parameters for ConnectRoom.
type ConnectRoomParams struct {
	Username *string `form:"username,omitempty" json:"username,omitempty"`
}

// CreateNewRoomJSONRequestBody defines body for CreateNewRoom for application/json ContentType.
type CreateNewRoomJSONRequestBody CreateNewRoomJSONBody
